In [1]:
from torchmetrics.regression import MeanAbsolutePercentageError

/home/infres/benaziza-22/anaconda3/envs/ima/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import time
t = time.time()

In [3]:
M = 6
M_hat = M
n_epochs = 300
val_len = 0.1
test_len = 0.1
lr = 1e-2
batch_size = 1024
enable_progress_bar = True
horizons = 3

In [28]:
# Install required packages.
from torchmetrics.regression import MeanAbsolutePercentageError
from torch.optim.lr_scheduler import MultiStepLR
from tsl.nn.models import DCRNNModel, GraphWaveNetModel, GatedGraphNetworkModel, RNNEncGCNDecModel
from tsl.nn.models import STCNModel, EvolveGCNModel, GRUGCNModel, AGCRNModel, GRINModel
import torch.nn as nn

from tsl.nn.blocks.encoders import RNN
from tsl.nn.layers import NodeEmbedding, DiffConv
from einops.layers.torch import Rearrange  # reshape data with Einstein notation


lr_milestones = [ 40, 80, 120]
scheduler_kwargs = dict(milestones=lr_milestones, gamma=0.25)
scheduler_class = MultiStepLR

import os
import torch
from tsl.metrics.torch import MaskedMSE, MaskedMAE, MaskedMAPE
from tsl.engines import Predictor

os.environ['TORCH'] = torch.__version__
print(torch.__version__)

device = 'cuda:1' if torch.cuda.is_available() else 'cpu'
print(device)

import shutil
# Get the current script file path
# script_path = os.path.realpath(__file__)
# Specify the destination file path
destination_path = './PemsBay_Results/'

if not os.path.isdir(destination_path):  
    os.mkdir(destination_path)
# Copy the current script to the destination
# shutil.copy2(script_path, destination_path)

2.3.0
cuda:1


In [29]:
from layers import CPGNN_ST, CPGNN_ST_v2, CPGNN_ST_v3, CITRUS, SGPModel
import networkx as nx
from Utilsss import get_evcs_evals
from pytorch_lightning.loggers import TensorBoardLogger
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, ProgressBar

import tsl
import torch
import torch_geometric
import numpy as np
import pandas as pd

print(f"torch version: {torch.__version__}")
print(f"  PyG version: {torch_geometric.__version__}")
print(f"  tsl version: {tsl.__version__}")

torch version: 2.3.0
  PyG version: 2.6.1
  tsl version: 0.9.5


In [30]:
# Plotting functions ###############
pd.options.display.float_format = '{:.2f}'.format
np.set_printoptions(edgeitems=3, precision=3)
torch.set_printoptions(edgeitems=2, precision=3)

In [31]:
# Utility functions ################
def print_matrix(matrix):
    return pd.DataFrame(matrix)

In [32]:
def print_model_size(model):
    tot = sum([p.numel() for p in model.parameters() if p.requires_grad])
    out = f"Number of model ({model.__class__.__name__}) parameters:{tot:10d}"
    print("=" * len(out))
    print(out)

In [48]:
from tsl.datasets import PemsBay
from tsl.datasets import MetrLA

# dataset = PemsBay(root='./PemsBay')
dataset = MetrLA(root='./MetrLA')

print(dataset)

MetrLA(length=34272, n_nodes=207, n_channels=1)


/home/infres/benaziza-22/anaconda3/envs/ima/lib/python3.12/site-packages/tsl/datasets/metr_la.py:98: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(df.index[0], df.index[-1], freq='5T')
/home/infres/benaziza-22/anaconda3/envs/ima/lib/python3.12/site-packages/tsl/datasets/metr_la.py:109: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df = df.replace(to_replace=0., method='ffill')


In [49]:

print(f"Sampling period: {dataset.freq}")
print(f"Has missing values: {dataset.has_mask}")
# print(f"Percentage of missing values: {(1 - dataset.mask.mean()) * 100:.2f}%")
print(f"Has exogenous variables: {dataset.has_covariates}")
print(f"Covariates: {', '.join(dataset.covariates.keys())}")


print_matrix(dataset.dist)

dataset.dataframe()

Sampling period: <5 * Minutes>
Has missing values: True
Has exogenous variables: True
Covariates: dist


nodes               773869 767541 767542 717447 717446 717445 773062 767620  \
channels                 0      0      0      0      0      0      0      0   
2012-03-01 00:00:00  64.38  67.62  67.12  61.50  66.88  68.75  65.12  67.12   
2012-03-01 00:05:00  62.67  68.56  65.44  62.44  64.44  68.11  65.00  65.00   
2012-03-01 00:10:00  64.00  63.75  60.00  59.00  66.50  66.25  64.50  64.25   
2012-03-01 00:15:00  64.00  63.75  60.00  59.00  66.50  66.25  64.50  64.25   
2012-03-01 00:20:00  64.00  63.75  60.00  59.00  66.50  66.25  64.50  64.25   
...                    ...    ...    ...    ...    ...    ...    ...    ...   
2012-06-27 23:35:00  65.00  65.89  68.56  61.67  32.83  54.56  62.44  63.33   
2012-06-27 23:40:00  61.38  65.62  66.50  62.75  32.83  50.50  62.00  67.00   
2012-06-27 23:45:00  67.00  59.67  69.56  61.00  32.83  44.78  64.22  63.78   
2012-06-27 23:50:00  66.75  62.25  66.00  59.62  32.83  53.00  64.29  64.12   
2012-06-27 23:55:00  65.11  66.89  66.78  61.22  32.83  49.56  65.78  65.11   

nodes               737529 717816  ... 772167 769372 774204 769806 717590  \
channels                 0      0  ...      0      0      0      0      0   
2012-03-01 00:00:00  59.62  62.75  ...  45.62  65.50  64.50  66.43  66.88   
2012-03-01 00:05:00  57.44  63.33  ...  50.67  69.88  66.67  58.56  62.00   
2012-03-01 00:10:00  63.88  65.38  ...  44.12  69.00  56.50  59.25  68.12   
2012-03-01 00:15:00  63.88  65.38  ...  44.12  69.00  56.50  59.25  68.12   
2012-03-01 00:20:00  63.88  65.38  ...  44.12  69.00  56.50  59.25  68.12   
...                    ...    ...  ...    ...    ...    ...    ...    ...   
2012-06-27 23:35:00  59.22  65.33  ...  52.89  69.00  65.11  55.67  66.33   
2012-06-27 23:40:00  65.25  67.12  ...  54.00  69.25  60.12  60.50  67.25   
2012-06-27 23:45:00  59.78  57.67  ...  51.33  67.89  64.33  57.00  66.00   
2012-06-27 23:50:00  60.88  66.25  ...  51.12  69.38  61.62  60.50  65.62   
2012-06-27 23:55:00  63.00  61.67  ...  56.00  67.44  64.89  60.89  64.22   

nodes               717592 717595 772168 718141 769373  
channels                 0      0      0      0      0  
2012-03-01 00:00:00  59.38  69.00  59.25  69.00  61.88  
2012-03-01 00:05:00  61.11  64.44  55.89  68.44  62.88  
2012-03-01 00:10:00  62.50  65.62  61.38  69.86  62.00  
2012-03-01 00:15:00  62.50  65.62  61.38  69.86  62.00  
2012-03-01 00:20:00  62.50  65.62  61.38  69.86  62.00  
...                    ...    ...    ...    ...    ...  
2012-06-27 23:35:00  62.44  66.78  64.89  69.67  62.33  
2012-06-27 23:40:00  59.38  66.00  61.25  69.00  62.00  
2012-06-27 23:45:00  62.67  68.67  63.33  67.44  61.22  
2012-06-27 23:50:00  66.38  69.50  63.00  67.88  63.50  
2012-06-27 23:55:00  66.44  68.44  63.56  68.67  61.78  

[34272 rows x 207 columns]

In [52]:
print(f"Default similarity: {dataset.similarity_score}")
print(f"Available similarity options: {dataset.similarity_options}")
print("==========================================")

# sim = dataset.get_similarity("stcn")  # or dataset.compute_similarity()
sim = dataset.get_similarity()  # or dataset.compute_similarity()
print("Similarity matrix W:")
print_matrix(sim)

Default similarity: distance
Available similarity options: {'distance'}
Similarity matrix W:


0    1    2    3    4    5    6    7    8    9    ...  197  198  199  \
0   1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.12   
1   0.00 1.00 0.39 0.00 0.00 0.00 0.00 0.39 0.00 0.00  ... 0.00 0.00 0.00   
2   0.00 0.72 1.00 0.00 0.00 0.00 0.00 0.09 0.00 0.00  ... 0.00 0.00 0.00   
3   0.00 0.00 0.00 1.00 0.63 0.00 0.01 0.00 0.00 0.00  ... 0.00 0.01 0.00   
4   0.00 0.00 0.00 0.63 1.00 0.05 0.14 0.00 0.00 0.00  ... 0.00 0.00 0.00   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.22  ... 0.13 0.00 0.00   
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.32 0.00   

     200  201  202  203  204  205  206  
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
1   0.00 0.03 0.00 0.00 0.00 0.00 0.00  
2   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
3   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
4   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
..   ...  ...  ...  ...  ...  ...  ...  
202 0.00 0.00 1.00 0.08 0.00 0.00 0.00  
203 0.00 0.00 0.00 1.00 0.00 0.00 0.00  
204 0.00 0.00 0.00 0.00 1.00 0.00 0.00  
205 0.00 0.00 0.00 0.00 0.00 1.00 0.00  
206 0.00 0.00 0.00 0.00 0.00 0.00 1.00  

[207 rows x 207 columns]

In [53]:
connectivity = dataset.get_connectivity(threshold=0.1,
                                        include_self=False,
                                        layout="edge_index",
                                        force_symmetric=True)

edge_index, edge_weight = connectivity

print(f'edge_index {edge_index.shape}:\n', edge_index)
print(f'edge_weight {edge_weight.shape}:\n', edge_weight)

edge_index (2, 2626):
 [[  0   0   0 ... 206 206 206]
 [ 13  36  37 ... 163 187 198]]
edge_weight (2626,):
 [0.261 0.519 0.509 ... 0.621 0.278 0.649]


In [54]:
from tsl.ops.connectivity import edge_index_to_adj

adj = edge_index_to_adj(edge_index, edge_weight)
print(f'A {adj.shape}:')
print_matrix(adj)

print(f'Sparse edge weights:\n', adj[edge_index[1], edge_index[0]])

A (207, 207):
Sparse edge weights:
 [0.261 0.519 0.509 ... 0.621 0.278 0.649]


In [55]:
from tsl.data import SpatioTemporalDataset

torch_dataset = SpatioTemporalDataset(target=dataset.dataframe(),
                                      connectivity=connectivity,
                                      mask=dataset.mask,
                                      horizon=horizons,
                                      window=M_hat,
                                      stride=1)
print(torch_dataset)

SpatioTemporalDataset(n_samples=34264, n_nodes=207, n_channels=1)


In [56]:

sample = torch_dataset[0]
# torch_dataset2 = torch_dataset[:1000]
print(sample)

Data(
  input=(x=[t=6, n=207, f=1], edge_index=[2, e=2626], edge_weight=[e=2626]),
  target=(y=[t=3, n=207, f=1]),
  has_mask=True
)


In [57]:

a = sample.input.to_dict()

b = sample.target.to_dict()

# if sample.has_mask:
#     print(sample.mask)
# else:
#     print("Sample has no mask.")

# if sample.has_transform:
#     print(sample.transform)
# else:
#     print("Sample has no transformation functions.")

In [58]:

print(sample.pattern)
print("==================   Or we can print patterns and shapes together   ==================")
print(sample)

{'x': 't n f', 'mask': 't n f', 'edge_index': '2 e', 'edge_weight': 'e', 'y': 't n f'}
==================   Or we can print patterns and shapes together   ==================
Data(
  input=(x=[t=6, n=207, f=1], edge_index=[2, e=2626], edge_weight=[e=2626]),
  target=(y=[t=3, n=207, f=1]),
  has_mask=True
)


In [59]:

batch = torch_dataset[:5]
print(batch)

StaticBatch(
  input=(x=[b=5, t=6, n=207, f=1], edge_index=[2, e=2626], edge_weight=[e=2626]),
  target=(y=[b=5, t=3, n=207, f=1]),
  has_mask=True
)


In [62]:

from tsl.data.datamodule import (SpatioTemporalDataModule,
                                 TemporalSplitter)
from tsl.data.preprocessing import StandardScaler

# Normalize data using mean and std computed over time and node dimensions
scalers = {'target': StandardScaler(axis=(0, 1))}

# Split data sequentially:
#   |------------ dataset -----------|
#   |--- train ---|- val -|-- test --|
splitter = TemporalSplitter(val_len=val_len, test_len=test_len)

dm = SpatioTemporalDataModule(
    dataset=torch_dataset,
    scalers=scalers,
    splitter=splitter,
    batch_size=batch_size,
)

# print(dm)

In [63]:

dm.setup()
print(dm)

{Train dataloader: size=27749}
{Validation dataloader: size=3077}
{Test dataloader: size=3426}
{Predict dataloader: None}


In [64]:
emb_size = 16    #@param
hidden_size = 32   #@param
rnn_layers = 1     #@param
gnn_kernel = 2   #@param

input_size = torch_dataset.n_channels   # 1 channel
n_nodes = torch_dataset.n_nodes         # 207 nodes
horizon = torch_dataset.horizon         # 12 time steps

In [65]:
# CGP_GNN = CGP_GNN_STGNN_betterImp(A=torch.tensor(adj).to(device), M=M_hat)

N = [n_nodes, M]
K_list = list(np.array(N)-2)
K_list = [323, M-2]


# G = nx.path_graph(N[0])

# G = nx.from_numpy_matrix(np.array(adj))

# AA = (adj+adj.T)/2

Graph_List = [nx.from_numpy_array(np.array(adj)), nx.path_graph(N[1])]

evecs, evals, L_list = get_evcs_evals(Graph_List, K_list)

for ii in range(len(evals)):
    evals[ii] = evals[ii].to(device)
    
    
CGP_GNN = CITRUS(input_size=input_size,
                            n_nodes=n_nodes,
                            horizon=horizon,
                            emb_size=emb_size,
                            hidden_size=hidden_size,
                            rnn_layers=rnn_layers,
                            gnn_kernel=gnn_kernel,
                            edge_index=torch.tensor(edge_index).to(device),
                            edge_weight=torch.tensor(edge_weight).to(device),
                            mass = torch.ones(np.prod(N)).to(device),
                            evals = evals,
                            evecs = torch.tensor(evecs).to(device),
                            C_width = 64,
                            N_block = 3,
                            single_t = True,
                            use_gdc = [],
                            num_nodes = N,
                            last_activation=torch.nn.ReLU(), 
                            mlp_hidden_dims=[64, 64, 64, 64], 
                            dropout=False, 
                            with_MLP=True, 
                            diffusion_method='spectral', 
                            device = device,
                            graph_wise=False)

              
print(CGP_GNN)
print_model_size(CGP_GNN)

loss_fn = MaskedMAE()

metrics = {'mse': MaskedMSE(),
           'mae': MaskedMAE(),
           'mape': MaskedMAPE()}


# setup predictor_CGP_GNN
# setup predictor
predictor_CGP_GNN = Predictor(
    model=CGP_GNN,                   # our initialized model
    optim_class=torch.optim.Adam,  # specify optimizer to be used...
    optim_kwargs={'lr': lr},    # ...and parameters for its initialization
    loss_fn=loss_fn,               # which loss function to be used
    metrics=metrics,
# metrics to be logged during train/val/test
)
logger_CGP_GNN = TensorBoardLogger(save_dir="FINAL_PemsBay_M6_H3", name="FINAL_PemsBay_M6_H3", version=0)

checkpoint_callback_CGPGNN = ModelCheckpoint(
    dirpath='FINAL_PemsBay_M6_H3',
    save_top_k=1,
    monitor='val_mae',
    mode='min',
)

trainer_CGP_GNN = pl.Trainer(max_epochs=n_epochs,
                      logger=logger_CGP_GNN,
                      accelerator='gpu',
                      devices=[1], 
#                      limit_train_batches=train_batches,  # end an epoch after 100 updates
                      callbacks=[checkpoint_callback_CGPGNN],
                      enable_progress_bar=enable_progress_bar)

t_CGPGNN = time.time()
trainer_CGP_GNN.fit(predictor_CGP_GNN, datamodule=dm)
elapsed = time.time() - t_CGPGNN
print('>>>>>>>>>>>>>>>>>>>> CGP-GNN training time, Elapsed: %s' % round(elapsed/60,2), ' minutes')

predictor_CGP_GNN.load_model(checkpoint_callback_CGPGNN.best_model_path)
predictor_CGP_GNN.freeze()



CGP_GNN_results = trainer_CGP_GNN.test(predictor_CGP_GNN, datamodule=dm);


#% Detailed metrics:

device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
XX = dm.testset
x_test = XX[:].x
y_test = XX[:].y
edge_index_test = XX[:].edge_index
edge_weight_test = XX[:].edge_weight

#CGPGNN:
print(10*'*')
print('CGPGNN:')    
y_pred = trainer_CGP_GNN.predict(predictor_CGP_GNN, dm.test_dataloader())
a = [y_pred[i]['y_hat'] for i in range(len(y_pred))]
y_pred = torch.cat(a, axis=0)
loss = nn.L1Loss()
MAE = loss(y_pred, y_test)
print(MAE)
MAPE = MeanAbsolutePercentageError()
MAPE = MAPE(y_pred, y_test)
print(MAPE)
loss = nn.MSELoss()
MSE = loss(y_pred, y_test)
print(MSE)
RelativeMAE = MAE/torch.abs(y_test).mean()
print(RelativeMAE)
RelativeMSE = MSE/((y_test**2).mean())
print(RelativeMSE)
Metrics_CGPGNN = [MAE.numpy(), MAPE.numpy(), MSE.numpy(),
                  RelativeMAE.numpy(), RelativeMSE.numpy()]

[323, 4]


/home/infres/benaziza-22/m2ds/graph_ml/CITRUS-Graph_ML/MetrLA_PemsBay/Utilsss.py:31: RuntimeWarning: k >= N - 1 for N * N square matrix. Attempting to use scipy.linalg.eig instead.
  evals, evecs = sparse.linalg.eigs(L_sparse, k=K_list[0], return_eigenvectors=True)


TypeError: Cannot use scipy.linalg.eig for sparse A with k >= N - 1. Use scipy.linalg.eig(A.toarray()) or reduce k.

In [ ]:
print(100*'*')
print('CGPGNN:')
print(Metrics_CGPGNN)

In [ ]:
elapsed = time.time() - t
print('Elapsed: %s' % round(elapsed/60,2), ' minutes')
print(600*'*')

